version: '3'

services: 
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  
  website:
    depends_on: 
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/brenbot'
    environment: 
      - LANG=C.UTF-8

volumes:
  postgres: